# Generated by Django 4.1.1 on 2022-09-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='session',
            field=models.CharField(blank=True, max_length=128, verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=64, verbose_name='Task'),
        ),
    ]
