# Generated by Django 4.1.1 on 2022-09-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='session',
        ),
    ]
