# Generated by Django 4.1.1 on 2022-09-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_todo_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='session',
            field=models.CharField(blank=True, max_length=128, verbose_name='Session'),
        ),
    ]
