# Generated by Django 4.1.1 on 2022-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='nanoid',
            field=models.CharField(default='s', max_length=25, unique=True, verbose_name='Nano id'),
            preserve_default=False,
        ),
    ]
