# Generated by Django 4.0 on 2022-10-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_todo_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='modified_at',
        ),
    ]
